SimoneCalzari/comus-frontend

- index.html
- src/assets/scss/general.scss
- src/assets/scss/partials/_reset.scss
- src/components/AppHeader.vue
- src/router.js
> feat: header

- src/components/AppSectionSlogan.vue
correzione section slogan in app home visibile da rifare il layout ma ora corretta
> feat: correction section

- src/components/AppRistoratore.vue
> feat: fix ristoratori

- src/components/AppJumboSearch.vue
- src/store.js
> feat: api img

- src/assets/scss/partials/_typography.scss
- src/components/AppDownload.vue
- src/components/AppFaq.vue
- src/components/AppFooter.vue
- src/components/AppJumbotron.vue
- src/components/AppList.vue
- src/components/AppRistoratore.vue
- src/components/AppSectionSlogan.vue
- fonts
- cambiati alcune classi e id
- spazi vuoti
> toFix: font in scss

- src/App.vue
- src/components/AppFooter.vue
- src/components/AppJumbotron.vue
- src/components/AppRistoratore.vue
- src/pages/AppHome.vue
> feat: refactor footer

- src/components/AppJumboSearch.vue
- src/components/AppRestaurantSingle.vue
- src/components/AppRestaurantsList.vue
- src/pages/AppHome.vue
> feat: search restaurants

- src/pages/AppRestaurantSingle.vue
> feat: restaurant

- src/components/AppJumbotron.vue
> fix: loop carosello

- src/components/AppJumboSearch.vue
- src/components/AppJumbotron.vue
- src/components/AppRestaurantsList.vue
> feat: jumbo

- src/components/AppJumboSearch.vue
- src/components/AppJumbotron.vue
- src/store.js
> Prove simone 

- src/components/AppDownload.vue
- src/components/AppRistoratore.vue
> feat: text-centered

- src/components/AppJumbotron.vue
- src/components/AppRestaurantsList.vue
- src/store.js
- refactor card ristoranti e card tipi
> Refactor style card type

- src/components/AppDish.vue
Fatto in maniera schifosa l'aggiustamento del carrello (si svuota se ordini da un altro ristorante)
> feat: u now cannot buy from more tham 1 restaurant LOL

- src/pages/AppShopping.vue
- src/store.js
> feat: order data customer

- src/App.vue
- src/components/AppDownload.vue
- src/components/AppFooter.vue
- src/components/AppHeader.vue
- src/components/AppRistoratore.vue
- src/components/AppSectionSlogan.vue
> feat: change costum in custom

- src/components/AppFaq.vue
- src/components/AppHeader.vue
- src/pages/AppShopping.vue
condizione assenza prodotto nel carrello
> feat: condizione assenza prodotto nel carrello

- src/components/AppPayment.vue
- src/pages/AppConfirmOrder.vue
- src/pages/AppShopping.vue
- src/router.js
> feat: orders/confirm

- src/components/AppRestaurantsList.vue
- src/pages/AppRestaurantSingle.vue
> feat: rest / dish numbers

- src/assets/scss/general.scss
- src/assets/scss/partials/_typography.scss
- src/components/AppJumbotron.vue
- src/pages/AppHome.vue
> feat: media query font

- src/components/AppJumbotron.vue
> Jumbo cards

- src/assets/scss/partials/_typography.scss
- src/components/AppRestaurantsList.vue
- src/components/AppSectionSlogan.vue
> feat: restaurants restyle

- src/components/AppDish.vue
- src/components/AppRestaurantsList.vue
> feat responsive restaurants

- src/assets/scss/partials/_typography.scss
- src/components/AppDownload.vue
> feat: downlaod

- src/components/AppDish.vue
- src/components/AppRestaurantsList.vue
- src/pages/AppRestaurantSingle.vue
- src/pages/AppShopping.vue
> feat: restyle dish

- src/components/AppRestaurantsList.vue
> feat: home

- src/components/AppFooter.vue
- src/components/AppHeader.vue
- src/components/AppSlogan.vue
> feat: refactor slogan

- src/components/AppRestaurantsList.vue
ciao, ho cambiato la posizione perche quando cambiavamo pagina, la nav andava verso giù perche il container delle card diventa più grande, quindi per una user exp migliore, la posizioniamo in cima
> fix:posizione pagination
